### ISSUE TITLE
Restructure wrapper class to present C# implementation as the primary one

### ISSUE THREAD

**Issue by Kinkyboo** [ZeroElectric/Raylib-CSharp-Vinculum#17]
Currently all DLL Imported Raylib functions are presented in intellisense before the C# implementation.
I don't know if this is possible to re-order but it would be a nice QoL change.

For example
RayGui.GuiScrollPanel first suggestion is:
`int RayGui.GuiScrollPanel(Rectangle bounds, sbyte* text, Rectangle content, Vector2* scroll, Rectangle* view)`

And second overload is the C# version:
`int RayGui.GuiScrollPanel(Rectangle bounds, string text, Rectangle content, ref Vector2 scroll, ref Rectangle view)`

**Comment by Minmoose** [comment]
I've somehow missed this, can't believe I'm not noticed this before, thanks for bringing it up! 

I've been attempting to find a fix for this, so far, I have not found one, if/when I do, I will make the necessary changes.

**Comment by Kinkyboo** [comment]
Perhaps mark any function that have a C# variant as internal instead of public,
If that is not possible perhaps rename the external functions with a "Ex" suffix
`int RayGui.GuiScrollPanelEx(Rectangle bounds, sbyte* text, Rectangle content, Vector2* scroll, Rectangle* view)`

**Comment by Minmoose** [comment]
Both renaming and making internal, would add unnecessary complexity to the auto generator, I also don't want to remove the ability to overload the original methods, so internal wouldn't work anyway.

The goal of the project is to be able to quickly update to a newer raylib version with minimal code change to the project, so adding complexity to the generator would potentially add more maintenance with every raylib update, something I wish to avoid.

**Comment by Kinkyboo** [comment]
After a bit of research I am not able to find a sustainable way re-order the overloads in intellisense.
Case closed.
