### ISSUE TITLE
LoadXFromMemory

### ISSUE THREAD

**Issue by akamicah** [ZeroElectric/Raylib-CSharp-Vinculum#9]
Binding looks good!

Do you have any plans to add methods like LoadTextureFromMemory(...) etc?

**Comment by danilwhale** [comment]
if you want to, you can create pull request with these methods

**Comment by Minmoose** [comment]
I couldn’t find `LoadTextureFromMemory()` in raylib’s API, however, I did find the following `LoadXFromMemory` functions:

`LoadImageFromMemory()` `LoadShaderFromMemory()` `LoadFontFromMemory()` `LoadWaveFromMemory()` `LoadMusicStreamFromMemory()`

all seem to work and have convenience wrappers for `sbyte*`, so unless I'm mistaken,
and you want `LoadTextureFromMemory()` specifically, you’ll need to submit a pull request or issue on the raylib repository.
